### ISSUE TITLE
PopOS Default App in light theme

### ISSUE THREAD

**Issue by CroissantDuNord** [witalihirsch/Mono-gtk-theme#1]
![image](https://user-images.githubusercontent.com/79372025/188280639-0dbef312-d05a-43d2-bab9-6bb315ac9e97.png)

**Comment by CroissantDuNord** [comment]
Screenshot issue
![image](https://user-images.githubusercontent.com/79372025/188280773-5fa9a0bf-5264-4693-b59f-f9d24a01df69.png)

**Comment by witalihirsch** [comment]
copy the contents of the gtk4.0 folder to .config/gtk4.0/ and show how it works

**Comment by CroissantDuNord** [comment]
Still in light theme

**Comment by witalihirsch** [comment]
what version of pop os are you using? i'll test

**Comment by CroissantDuNord** [comment]
22.04 (LTS) With GNOME 42.4

**Comment by witalihirsch** [comment]
honestly idk why gtk4 theme don't work in PopOS. everything works on clean gnome

**Comment by osieltorres** [comment]
> honestly idk why gtk4 theme don't work in PopOS. everything works on clean gnome

It works on Pop!_OS 22.04, nicely, @CroissantDuNord it should be something related with your settings. I also use same version of Pop!_OS and works!.
As a final note, one thing I could ask is that it also enables theme in lock screen, which currently does not get applied, I double check the steps in the instructions, and the only place where theme is not applied is in lock screen, which gets default Pop!_OS theme(light version).
![image](https://user-images.githubusercontent.com/3835402/198814170-e3ca881e-5025-4f00-996d-e995890b9403.png)
