### ISSUE TITLE
Terminator tabs keep transparent

### ISSUE THREAD

**Issue by antun3s** [witalihirsch/Mono-gtk-theme#10]
First, I need to say, this theme is really beautiful. Thanks for your job.
I like to use Terminator as my terminal emulator, but the tabs keep transparent.
![Monogtktheme-terminator-tab](https://user-images.githubusercontent.com/6098562/194699549-7d275a34-18e3-4cf8-83ef-390a6550d699.png)
How I can fix it?

Manjaro Linux 22.0.0 Sikaris
GNOME Shell 42.5

**Comment by witalihirsch** [comment]
fixed
