### ISSUE TITLE
Nautilus on Gnome 43 looks broken.

### ISSUE THREAD

**Issue by heymde0x541** [witalihirsch/Mono-gtk-theme#13]
![image](https://user-images.githubusercontent.com/99078610/197417800-151d55fb-2100-4c7c-ae4d-b94c1d9ee901.png)

First of all, I'd like to thank you for the amazing theme you've made.

Issue: Nautilus on gnome 43 looks broken. Width is inconsistent around the titlebars and stuff. (Sorry for my poor english.)

**Comment by heymde0x541** [comment]
whoops, sorry. My bad. I accidentally closed the issue.

**Comment by witalihirsch** [comment]
fixed. see last release

**Comment by heymde0x541** [comment]
awesome work!
