### ISSUE TITLE
Dark Background in Light theme inside overview effect (Gnome 43)

### ISSUE THREAD

**Issue by heymde0x541** [witalihirsch/Mono-gtk-theme#14]
![image](https://user-images.githubusercontent.com/99078610/198022456-f4ce0455-f299-4c93-83a1-f96b27a1685a.png)

This makes the top bar disappear because of dark text on dark background. 

https://gitlab.gnome.org/eeshugerman/gnome-shell-theme-default-light/
I don't know, this theme might help you to solve this.

🥰

**Comment by witalihirsch** [comment]
fixed a problem with an invisible color on the panel in the overview, about the light background in the overview, i'll think about how to do it better
you can try `blur my shell` extension and in tab overview > background blur > overview components style > `do not style` and it will look like this
![image](https://user-images.githubusercontent.com/73841541/200604939-2b7edaa2-26fa-4721-b5c2-5c4500cd3adf.png)
![Screenshot from 2022-11-08 21-22-22](https://user-images.githubusercontent.com/73841541/200605204-d28c9fb5-b217-48c1-8d4b-b5ee3169cd01.png)
