### ISSUE TITLE
Pop!_OS launcher input font almost invisible in dark theme version

### ISSUE THREAD

**Issue by osieltorres** [witalihirsch/Mono-gtk-theme#15]
I use Pop!_OS with version 22.04 LTS. I love the theme and in order to make it better even, I am sharing this issue related to the launcher input font, which get almost invisible in theme dark variant.
On the image you can see the placeholder text is almost not readable.
![image](https://user-images.githubusercontent.com/3835402/198814320-ff6fe69e-88e9-4bda-a6c5-1a1b4a4f03ea.png)

**Comment by witalihirsch** [comment]
what is this launcher, default in PopOS?

**Comment by osieltorres** [comment]
> what is this launcher, default in PopOS?

Yes, is the default Pop!_OS launcher, I recently noticed that this also happens to the Application grid(se screenshot below)
![image](https://user-images.githubusercontent.com/3835402/198862655-11c766d8-b3ff-4c55-864f-3d1b9d1b564e.png)

**Comment by witalihirsch** [comment]
![image](https://user-images.githubusercontent.com/73841541/198874038-0eed85ca-c05e-42db-bf7d-c3920f21371a.png)
![image](https://user-images.githubusercontent.com/73841541/198874046-a04c81ac-4916-4b3e-a181-ba80ae96bdcf.png)

**Comment by witalihirsch** [comment]
try updating the theme for gnome-shell to the latest one if you haven't updated

**Comment by osieltorres** [comment]
@witalihirsch that worked, I updated the theme and no works fine. Thanks!
