### ISSUE TITLE
Theme version is not applied to lock screen in Pop!_OS

### ISSUE THREAD

**Issue by osieltorres** [witalihirsch/Mono-gtk-theme#16]
Hi!, first of all, thanks for the amazing theme.
The issue I am facing is related to setting the theme(in any alternative) for the lock screen. I must say after follow the instructions everything worked fine until I left the laptop for a while and it got locked, then I realized theme had not been applied for lock screen(it kept the Pop!_OS default theme in light version).
I think, from a global perspective, this is the only thing missing IMO to be completely usable by anyone.
Here the screenshot
![image](https://user-images.githubusercontent.com/3835402/198814773-c0aeaa25-ddae-46dd-8dc2-9b5664a45308.png)

**Comment by witalihirsch** [comment]
did you follow all the instructions exactly? for the theme to work on the lock screen and login screen, you need to follow these steps:
IMPORTANT! Take a snapshot of the system before use!
If you want the gnome-shell theme to extend to the lock and login screen, move the gnome-shell-theme.gresource file from gnome-shell folder to /usr/share/gnome-shell/ with a replacement and restart system with ALT+F2 and enter r for Xorg or reboot/log out for Wayland session.
Command:
sudo cp gnome-shell-theme.gresource /usr/share/gnome-shell
![Screenshot from 2022-10-29 13-43-02](https://user-images.githubusercontent.com/73841541/198820234-c02680eb-0e66-40e0-94e7-241a0802c105.png)

**Comment by osieltorres** [comment]
I did, as I said, I followed and double check the instructions, but unfortunately, it did not work, in the case of lock screen, Pop!_OS default theme is set(Light version)

**Comment by osieltorres** [comment]
Well, I think I found a workaround. In addition to the instructions, I had to add two more steps:
1. Copy the theme folder(Light or Dark version) into `/usr/share/gnome-shell/theme/` and, in my case I just rename it to "Mono"
2. Edit the file `/usr/share/gnome-shell/modes/pop.json` and change this line: 
`"theme/Pop/gnome-shell-theme.gresource"` 
to this:
`"theme/Mono/gnome-shell-theme.gresource"`
Now works fine in all cases.

**Comment by witalihirsch** [comment]
good thing it worked :)
i'll try to figure out what the problem is

**Comment by witalihirsch** [comment]
😂
![image](https://user-images.githubusercontent.com/73841541/198874430-ec9cdb31-fe87-4a7a-8914-1d57d5440cd4.png)
in general, i think it was a conflict between my gnome-shell and gnome-shell PopOS, so it's enough to replace the gresource file in the Pop folder with my version

**Comment by witalihirsch** [comment]
but it seems i broke the system anyway

**Comment by osieltorres** [comment]
I think because Pop!_OS is built on top of Ubuntu, that makes we need to add those two additional steps, but in vanilla gnome(fedora), it works as per theme instructions.
