### ISSUE TITLE
gnome-themes isn't detected by gnome tweaks

### ISSUE THREAD

**Issue by illegitimate-egg** [witalihirsch/Mono-gtk-theme#2]
I put gnome-themes into my .themes folder and it doesn't show up in gnome tweaks :/

**Comment by witalihirsch** [comment]
gtk4 are installed differently. copy the contents of the gtk4.0 folder to .config/gtk4.0/

**Comment by illegitimate-egg** [comment]
I uh.. did?

**Comment by illegitimate-egg** [comment]
Then I rebooted and now some parts of default apps are in light mode and other parts are in dark mode :/

**Comment by witalihirsch** [comment]
works?

**Comment by illegitimate-egg** [comment]
no

**Comment by witalihirsch** [comment]
this is due to the fact that the gtk3 theme is still in development, expect a new release
![image](https://user-images.githubusercontent.com/73841541/188303369-ae4473bc-49e3-4f76-9826-da20de25aebb.png)

**Comment by illegitimate-egg** [comment]
Oh ok
