### ISSUE TITLE
Mail list unreadable in Evolution

### ISSUE THREAD

**Issue by Ziiga** [witalihirsch/Mono-gtk-theme#21]
The e-mail list in Evolution uses light on light text with the dark gtk3 theme and dark on dark with the light gtk3 theme. This makes it extremely difficult read.
![slika](https://user-images.githubusercontent.com/47578932/203463702-181aeabe-4055-4ca7-83b1-f1815a12fff3.png)
![slika](https://user-images.githubusercontent.com/47578932/203463737-ce79539e-9068-49fa-9249-80e4390e5267.png)

MonoTheme version: 0.8
Evolution version: 3.46.1
Gnome version: 43.1

**Comment by witalihirsch** [comment]
thanks for your feedback, fixed
