### ISSUE TITLE
include an index.theme so gnome-tweaks can pick up each theme

### ISSUE THREAD

**Issue by OnlyCS** [witalihirsch/Mono-gtk-theme#24]
Example `index.theme`
```
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=MonoThemeDark
Comment=index.theme test
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=MonoThemeDark
ButtonLayout=close,minimize,maximize:menu
```

Example directory structure
```
~/.themes
└── MonoThemeDark
│   ├── gnome-shell
│   │   ├──...
│   ├── gtk-3.0
│   │   ├──...
│   ├── gtk-4.0
│   │   ├──...
│   └── index.theme
└── MonoTheme
    ├── gnome-shell
    │   ├──...
    ├── gtk-3.0
    │   ├──...
    ├── gtk-4.0
    │   ├──...
    └── index.theme
```

`~/.config/gtk-4.0/*` should be linked to the contents of `~/.themes/MonoThemeDark/gtk-4.0/*` 
(see: https://github.com/odziom91/libadwaita-theme-changer)

**Comment by witalihirsch** [comment]
check last commit, but i'm not sure i made all right. if i made something wrong, i'll be glad for your help

**Comment by OnlyCS** [comment]
yes, it works fine. `index.theme` (in user themes) only contains some metadata about the theme, like the name and description
