### ISSUE TITLE
Re: Gap in the top bar in gtk3 application (Gnome-Tweaks)

### ISSUE THREAD

**Issue by eshate** [witalihirsch/Mono-gtk-theme#27]
> **fixed (thanks 😊)**
> _Originally posted by @witalihirsch in https://github.com/witalihirsch/Mono-gtk-theme/issues/6#issuecomment-1262015333_

Hey. That's strange, because this post is from September. I am using the newest version of the theme and the problem is still there. I suppose that I had different version installed before - but how to clear the cache or to be sure that I've uninstalled the previous version the right way? Because I recall that I was uninstalling the past version...

Also, I think that I saw more of these gaps, but I cannot tell exactly where now. I will look for it. 

![Screenshot from 2023-01-08 06-10-02](https://user-images.githubusercontent.com/74292287/211181678-245e03a3-b886-4bad-a9ea-7ef8fc290a64.png)

**Comment by witalihirsch** [comment]
is the issue still relevant? i don't have that bug.
![image](https://user-images.githubusercontent.com/73841541/217762706-c6579a3f-504c-4ee5-a6e6-99aa8191d527.png)
