### ISSUE TITLE
Bug: No visual indicators for split screening apps

### ISSUE THREAD

**Issue by mbeps** [witalihirsch/Mono-gtk-theme#3]
Normally, when dragging an app on the other side of screen for tiling, there is a rectangle as visual indicator. The indicator for this theme is present but it is too transparent to be visible. 

**Defective Behaviour**
https://user-images.githubusercontent.com/58662575/188325764-985750b0-aef1-4397-8985-a23ba00c3d40.mp4

**Expected Behaviour (Default Theme)**
https://user-images.githubusercontent.com/58662575/188325881-a6033e8e-5dab-47a5-8a46-bf4d3b608487.mp4

**Comment by witalihirsch** [comment]
that's better?

https://user-images.githubusercontent.com/73841541/188475525-79d6a04a-9e4c-4cd7-a2a8-4b702a03886c.mp4

**Comment by mbeps** [comment]
Yes, it seems fine now. Thanks.
