### ISSUE TITLE
TOP BAR INACTIVE TERMINAL WINDOW GTK3 ISSUE (different colors accents)

### ISSUE THREAD

**Issue by styeff** [witalihirsch/Mono-gtk-theme#30]
Hello, I report this issue, as explained in top title and shown following, hoping for an early fix, thank you! ![Schermata del 2023-01-20 15-53-18](https://user-images.githubusercontent.com/101471099/213729204-477a4eaf-801c-443e-bf98-deddfc415bcc.png)

**Comment by witalihirsch** [comment]
this issue concerns only the terminal and as I realized it, the terminal window itself doesn't apply to gtk3, but is styled in a different way. all I could do was change the color of the active window. same problem is in other themes

**Comment by styeff** [comment]
> this issue concerns only the terminal and as I realized it, the terminal window itself doesn't apply to gtk3, but is styled in a different way. all I could do was change the color of the active window. same problem is in other themes

Thanks you!

**Comment by witalihirsch** [comment]
if I can figure out how to tweak this I'll do it in a future release
