### ISSUE TITLE
mono theme issue with chrome

### ISSUE THREAD

**Issue by pushkargogte** [witalihirsch/Mono-gtk-theme#36]
can you fix this mono theme issue with chrome?
I know that this issue is due to chrome but can you to try fix it?

(https://github.com/vinceliuice) has mitigated the issue in his whitesur, orchis, jasper themes

![image](https://user-images.githubusercontent.com/16486468/217439730-b611c531-b2e1-4104-bf26-9c8743043e8f.png)

![image](https://user-images.githubusercontent.com/16486468/217438922-3ef97db2-8202-45a3-b19d-3a2f0d1879bb.png)

**Comment by witalihirsch** [comment]
fixed

**Comment by pushkargogte** [comment]
> fixed

thank you. one more thing i have notice, when multiple tabs are open in terminator terminal in ubuntu 22.04.1 few gaps are seen

i have highlighted few, other can be seen on the right end and the bottom end

![image](https://user-images.githubusercontent.com/16486468/217999784-464443c1-7513-4793-885b-a6700912fbd3.png)

**Comment by pushkargogte** [comment]
except transperancy below tabs all other borders are fixed 

![image](https://user-images.githubusercontent.com/16486468/218643491-84f3dd00-947b-46ab-9969-392bdf446061.png)

**Comment by witalihirsch** [comment]
check now

**Comment by pushkargogte** [comment]
> check now

its fixed, thanks for quick action :)
