### ISSUE TITLE
GNOME 44 issues

### ISSUE THREAD

**Issue by Drsheppard01** [witalihirsch/Mono-gtk-theme#40]
Проблема со съезжающими кнопками в панели управления

![Снимок экрана от 2023-03-25 06-54-55](https://user-images.githubusercontent.com/60893791/227691861-6629ee8f-6b5f-4e44-85d6-9fbf9cdcf701.png)

На втором скриншоте при наведении текст становится белым (меню из расширения application menu)

![Снимок экрана от 2023-03-25 06-55-11](https://user-images.githubusercontent.com/60893791/227691905-17ccb0d0-415e-411a-a50f-dab2af7faf71.png)

**Comment by DannyFatty707** [comment]
![image](https://user-images.githubusercontent.com/96933224/234443219-c94f2b21-c036-4c0f-8258-164381138d44.png)
Yeah, it happens the same to me. Buttons in Quick Settings (GNOME 44) appear weird after upgrading to GNOME 44. The arrows to the Settings are separated from the main button

**Comment by nothingneko** [comment]
Same issue here
![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/37665485/dc9f2f4e-8c0d-4836-a745-baa195321f09)

**Comment by rebatnaath** [comment]
please fix this please

**Comment by tech-karim** [comment]
i am working on a fix i'll be done soon

**Comment by nothingneko** [comment]
thanks!

**Comment by tech-karim** [comment]
you're welcome
