### ISSUE TITLE
Some issues in GNOME 44

### ISSUE THREAD

**Issue by Drsheppard01** [witalihirsch/Mono-gtk-theme#46]
![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/60893791/a2306a66-6f45-452e-94dc-e893782b21ac)

This box in quick-settings
I unfortunately couldn't find exactly what it's named, but I did find this guide about gnome javascript (gjs)

As well as these lines https://github.com/vinceliuice/Qogir-theme/blob/master/src/gnome-shell/theme-44-0/gnome-shell.css#L216

Moreover, i has problem with white text when hovering in the context menu 

![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/60893791/95eeb68e-429a-4bbe-8c06-66ee59cae0a8)

There is the same error in screenshot-ui and the same error with saving apps-menu

**Comment by tech-karim** [comment]
i'll be taking a look a it soon

**Comment by tech-karim** [comment]
i found the issue but idk the correct look for it can someone  provide an example
