### ISSUE TITLE
Sumbit this theme as preset for Gradience

### ISSUE THREAD

**Issue by daudix-UFO** [witalihirsch/Mono-gtk-theme#7]
Hello, first, Thank you for such an amazing theme, it looks just fantastic!

If you interested you can add this theme to the [Gradience](https://github.com/GradienceTeam/Gradience) as a Preset

https://github.com/GradienceTeam/Community#how-to-add

**Comment by witalihirsch** [comment]
it's interesting, but there are quite a few features for customization

**Comment by daudix-UFO** [comment]
OK, thank you;)
